version: 1
reviews:
  auto_review:
    enabled: true
    on:
      pull_request:
        # review non-default branches too
        target_branches: ["*"]
        base_branches: ["*"]
    trigger:
      comments:
        enabled: true
        commands: ["review"]
  review_status: true   # show the status check in PR
  profile: CHILL        # matches what CodeRabbit reported
paths:
  include:
    - "backend/**"
    - "frontend/**"
tools:
  ruff:
    enabled: true