# .github/coderabbit.yml

reviews:
  auto_review: true          # Run reviews automatically on all PRs
  inline_comments: true      # Leave comments directly on lines of code
  summary: true              # Provide a summary review at the end
  request_changes: false     # Don’t block merges (set true if you want stricter enforcement)
  review_status: true        # Show review status in PR checks

branches:
  include: ["*"]             # Review all branches (not just main)